# APP
version: '3'
services:
  db:
    container_name: auction_mysql
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: rmt-auction
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - "./docker/mysql_data/data:/var/lib/mysql"
      - "./docker/mysql_data/my.cnf:/etc/mysql/conf.d/my.cnf"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: on-failure
  redis:
    container_name: rmt-auction_redis
    image: bitnami/redis:6.2.6
    environment:
      # Recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "./docker/redis_data:/bitnami/redis/data"
    ports:
      - "6379:6379"
    restart: on-failure
  api:
    container_name: rmt-auction_api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - docker/.env
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms256m
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    restart: on-failure
  nginx:
    image: nginx:1.19.0
    container_name: rmt_auction_nginx
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/config/sites/:/etc/nginx/conf.d/
      - ./docker/logs:/var/log/nginx/
    depends_on:
      - api
