server:
  port: 8083

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}
    validation-query: SELECT 1
    hikari:
      poolName: Hikari
      auto-commit: false
      schema: ${DB_SCHEMA}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: false
        default_schema: ${DB_SCHEMA}

#config using by common lib
error:
  path: classpath:i18n/error_messages
jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_BASE64_SECRET:QnP/dJWnqc9AYMokt8yPjUqDNSPKk/yS+AFy4D0LZMy2BXAC4uGSXzk2x+P11uly5WYXSRQ5qvDboHXaf+pjyw==}

application:
  internal-clients:
    uaa:
      base-uri: ${UAA_URI:http://localhost:8082/api/v1/auth}
    master:
      base-uri: ${MASTER_DATA_URI:http://localhost:8084/api/v1}
  file-upload:
    max-size-allow: 10240
    allow-extensions: png, jpg, jpeg, gif

amazon:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    temp-dir: /tmp
    working-dir: /working
    use-iam-role: false
    s3-url: ${AWS_S3_URL:https://em-project-s3.s3.ap-southeast-1.amazonaws.com}
