server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterSetResults=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
    validation-query: SELECT 1
    hikari:
      poolName: Hikari
      auto-commit: false
      schema: ${DB_SCHEMA}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        default_schema: ${DB_SCHEMA}
    hibernate:
      ddl-auto: none

#config using by common lib
error:
  path: classpath:i18n/error_messages
