---
- name: Install python-pip package
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Install python-pip package
  apt:
    name: python-pip
    state: present
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install docker pip packages
  pip:
    name: docker
    state: present
    extra_args: "--user"
  when: env == 'dev'
  
- name: Ansible check app directory exists.
  stat:
    path: "{{ application_path }}"
  register: check_app_dir

- name: Create app directory
  file:
    path: "{{ application_path }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  when: not check_app_dir.stat.exists
