---
env: "dev"
git_repo: "git@bitbucket.org:nal-solutions/rmt-auction.git"
branch: "develop"
repos: "rmt-auction"
username: "dev"
user_home_folder: "/home/{{ username }}"
container_port: 8083
host_port: 8083
DB_SCHEMA: "auction"
